# Generated by Django 4.1.3 on 2022-11-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=6)),
                ('age', models.SmallIntegerField()),
                ('motherTongue', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('hobby', models.TextField()),
                ('contactno', models.CharField(max_length=15)),
                ('emailaddress', models.EmailField(max_length=254)),
            ],
        ),
    ]
